from . import types, exceptions, localization


STEP_PREFIXES = {
    "en": # English
    [
        ("Feature: ", types.FEATURE),
        ("Scenario Outline: ", types.SCENARIO_OUTLINE),
        ("Examples: Vertical", types.EXAMPLES_VERTICAL),
        ("Examples:", types.EXAMPLES),
        ("Scenario: ", types.SCENARIO),
        ("Background:", types.BACKGROUND),
        ("Given ", types.GIVEN),
        ("When ", types.WHEN),
        ("Then ", types.THEN),
        ("@", types.TAG),
        # Continuation of the previously mentioned step type
        ("And ", None),
        ("But ", None),
    ],
    "es": # Spanish/Español
    [
        ("Característica: ", types.FEATURE),
        ("Esquema del escenario: ", types.SCENARIO_OUTLINE),
        ("Ejemplos: Vertical", types.EXAMPLES_VERTICAL),
        ("Ejemplos: ", types.EXAMPLES),
        ("Escenario: ", types.SCENARIO),
        ("Antecedentes:", types.BACKGROUND),
        ("Dada ", types.GIVEN),
        ("Dado ", types.GIVEN),
        ("Dadas ", types.GIVEN),
        ("Dados ", types.GIVEN),
        ("Cuando ", types.WHEN),
        ("Entonces ", types.THEN),
        ("@", types.TAG),
        ("E ", None),
        ("Y ", None),
        ("Pero ", None),
    ],
    "pt": # Portuguese/Português
    [
        ("Caracteristica: ", types.FEATURE),
        ("Característica: ", types.FEATURE),
        ("Funcionalidade: ", types.FEATURE),
        ("Esquema do Cenario: ", types.SCENARIO_OUTLINE),
        ("Esquema do Cenário: ", types.SCENARIO_OUTLINE),
        ("Delineacao do Cenario: ", types.SCENARIO_OUTLINE),
        ("Delineação do Cenário: ", types.SCENARIO_OUTLINE),
        # EXAMPLES_VERTICAL?
        ("Cenarios:", types.EXAMPLES),
        ("Cenários:", types.EXAMPLES),
        ("Exemplos:", types.EXAMPLES),
        ("Exemplo: ", types.SCENARIO),
        ("Cenario: ", types.SCENARIO),
        ("Cenário: ", types.SCENARIO),
        ("Cenario de Fundo:", types.BACKGROUND),
        ("Cenário de Fundo:", types.BACKGROUND),
        ("Contexto:", types.BACKGROUND),
        ("Fundo:", types.BACKGROUND),
        ("Dada ", types.GIVEN),
        ("Dado ", types.GIVEN),
        ("Dadas ", types.GIVEN),
        ("Dados ", types.GIVEN),
        ("Quando ", types.WHEN),
        ("Entao ", types.THEN),
        ("Então ", types.THEN),
        ("@", types.TAG),
        ("E ", None),
        ("Mas ", None),
    ],
    "de": # German/Deutsch
    [
        ("Funktion: ", types.FEATURE),
        ("Funktionalität: ", types.FEATURE),
        ("Szenarien: ", types.SCENARIO_OUTLINE),
        ("Szenariogrundriss: ", types.SCENARIO_OUTLINE),
        # EXAMPLES_VERTICAL?
        ("Beispiele:", types.EXAMPLES),
        ("Beispiel: ", types.SCENARIO),
        ("Szenario: ", types.SCENARIO),
        ("Grundlage:", types.BACKGROUND),
        ("Hintergrund:", types.BACKGROUND),
        ("Voraussetzungen:", types.BACKGROUND),
        ("Vorbedingungen:", types.BACKGROUND),
        ("Angenommen ", types.GIVEN),
        ("Gegeben sei ", types.GIVEN),
        ("Gegeben seien ", types.GIVEN),
        ("Wenn ", types.WHEN),
        ("Dann ", types.THEN),
        ("@", types.TAG),
        ("Und ", None),
        ("Aber ", None),
    ],
}